'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words={
 pickupPoint:['נקודת האיסוף','Pickup point','Место подачи','Місце подачі'],driverAccepted:['בדרך לאיסוף','On the way to pickup','В пути к пассажиру','У дорозі до пасажира'],
 title:['לאן נוסעים?','Where to?','Куда едем?','Куди їдемо?'],subtitle:['מזמינים מונית בכל אוקראינה.','Book a taxi across Ukraine.','Заказ такси по всей Украине.','Замовлення таксі по всій Україні.'],
 gpsTitle:['קודם, המיקום שלך','First, your location','Сначала ваша геопозиция','Спочатку ваша геопозиція'],gpsText:['שיתוף GPS הוא תנאי להזמנת נסיעה. נשתמש בו לנקודת האיסוף ולתקשורת עם הנהג.','Share GPS to request a ride. It is used for pickup and coordination with your driver.','Поделитесь GPS для заказа поездки и встречи с водителем.','Поділіться GPS для замовлення поїздки та зустрічі з водієм.'],
 gps:['שיתוף המיקום שלי','Share my location','Поделиться геопозицией','Поділитися геопозицією'],demoGPS:['שימוש במיקום הדגמה','Use demo location','Использовать демо GPS','Використати демо GPS'],gpsTrust:['המיקום משותף רק לצורך הנסיעה ומוצג במפת OpenStreetMap. אפשר להפסיק שיתוף בבוט.','Location is shared for your ride and displayed on OpenStreetMap. Stop sharing in the bot.','Геопозиция используется для поездки и карты OpenStreetMap. Остановить передачу можно в боте.','Геопозиція використовується для поїздки та карти OpenStreetMap. Зупинити передачу можна в боті.'],
 pickup:['המיקום שלי · GPS','My location · GPS','Моя геопозиция · GPS','Моя геопозиція · GPS'],destination:['עיר, רחוב ומספר בית','Destination address or place','Адрес или место назначения','Адреса або місце призначення'],passengers:['מספר נוסעים','Passengers','Пассажиры','Пасажири'],popular:['מסלולים נפוצים','Popular routes','Популярные маршруты','Популярні маршрути'],custom:['כתובת חופשית','Custom address','Другой адрес','Інша адреса'],
 request:['בקשת הצעות מחיר','Request driver prices','Запросить цены','Запросити ціни'],priceNote:['הנהגים מציעים מחיר בגריבנה. רק לאחר האישור שלך, הנהג משובץ.','Drivers quote in hryvnia. A driver is booked only after your acceptance.','Водители предлагают цену в гривнах. Назначение — после вашего согласия.','Водії пропонують ціну в гривнях. Призначення — після вашої згоди.'],
 ride:['הנסיעה שלי','My ride','Моя поездка','Моя поїздка'],history:['היסטוריה','History','История','Історія'],cancel:['ביטול הבקשה','Cancel request','Отменить заказ','Скасувати замовлення'],waiting:['מחפשים את הנהג שלך','Finding your driver','Ищем вашего водителя','Шукаємо вашого водія'],waitingText:['הבקשה נשלחה לנהגים המתאימים. ההצעות יופיעו כאן.','Your request is with eligible drivers. Quotes will appear here.','Запрос отправлен подходящим водителям. Предложения появятся здесь.','Запит надіслано відповідним водіям. Пропозиції з’являться тут.'],offers:['ההצעות שלך','Your driver quotes','Ваши предложения','Ваші пропозиції'],choose:['אישור מחיר והזמנה','Accept price & book','Принять цену и заказать','Прийняти ціну й замовити'],total:['לכל הנסיעה','Total trip price','За всю поездку','За всю поїздку'],
 accepted:['הנהג בדרך אליך','Your driver is on the way','Водитель едет к вам','Водій їде до вас'],arrived:['הנהג הגיע לאיסוף','Your driver has arrived','Водитель прибыл','Водій прибув'],in_progress:['נסיעה טובה!','Enjoy your ride!','Приятной поездки!','Гарної поїздки!'],completed:['הנסיעה הושלמה','Ride completed','Поездка завершена','Поїздку завершено'],cancelled:['הנסיעה בוטלה','Ride cancelled','Поездка отменена','Поїздку скасовано'],searching:['ממתינים להצעות','Awaiting quotes','Ожидаем предложения','Очікуємо пропозиції'],quoted:['מוכן לשליחה','Ready to request','Готово к отправке','Готово до надсилання'],
 message:['כתבו הודעה…','Write a message…','Напишите сообщение…','Напишіть повідомлення…'],send:['שליחה','Send','Отправить','Надіслати'],chat:['שיחה עם הצד השני','Ride conversation','Чат поездки','Чат поїздки'],call:['חיוג לנהג','Call driver','Позвонить водителю','Зателефонувати водію'],location:['עדכון GPS','Update GPS','Обновить GPS','Оновити GPS'],noMessages:['כאן אפשר לתאם את נקודת המפגש.','Coordinate your meeting point here.','Здесь можно уточнить место встречи.','Тут можна уточнити місце зустрічі.'],
 driverTitle:['נהגים: הרשמה וקבלת נסיעות','Driver area','Кабинет водителя','Кабінет водія'],online:['זמין לנסיעות','Online for rides','На линии','На лінії'],offline:['לא זמין','Offline','Не на линии','Не на лінії'],goOnline:['הפעלת זמינות','Go online','Выйти на линию','Вийти на лінію'],goOffline:['הפסקת זמינות','Go offline','Уйти с линии','Піти з лінії'],quote:['שליחת הצעת מחיר','Send price quote','Предложить цену','Запропонувати ціну'],price:['המחיר שלך בגריבנה','Your price in hryvnia','Ваша цена в гривнах','Ваша ціна в гривнях'],decline:['דחייה','Decline','Отклонить','Відхилити'],offered:['המחיר נשלח. ממתינים לאישור הנוסע.','Quote sent. Waiting for passenger approval.','Цена отправлена. Ждём пассажира.','Ціну надіслано. Чекаємо пасажира.'],noJobs:['אין כרגע בקשות חדשות.','No new requests right now.','Пока нет новых заказов.','Поки немає нових замовлень.'],arrive:['הגעתי לאיסוף','I have arrived','Я на месте','Я на місці'],start:['התחלת נסיעה','Start ride','Начать поездку','Почати поїздку'],finish:['סיום נסיעה','Complete ride','Завершить поездку','Завершити поїздку'],
 noHistory:['הנסיעות שלך יופיעו כאן.','Your past rides will appear here.','Здесь появятся ваши поездки.','Тут з’являться ваші поїздки.'],rate:['איך הייתה הנסיעה?','How was the ride?','Как прошла поездка?','Як пройшла поїздка?'],error:['הפעולה לא הושלמה. בדקו את הפרטים או רעננו מיקום ונסו שוב.','Action could not be completed. Check the details or refresh GPS and retry.','Действие не выполнено. Проверьте данные или обновите GPS.','Дію не виконано. Перевірте дані або оновіть GPS.'],denied:['אין גישה למיקום. יש לאשר הרשאת GPS בטלגרם או בדפדפן.','Location is unavailable. Allow GPS in Telegram or your browser.','Нет доступа к GPS. Разрешите геопозицию в Telegram или браузере.','Немає доступу до GPS. Дозвольте геопозицію в Telegram або браузері.'],auth:['יש לפתוח את הממשק מתוך הבוט בטלגרם.','Open this app from the Telegram bot.','Откройте приложение из бота Telegram.','Відкрийте застосунок із бота Telegram.'],saved:['עודכן בהצלחה','Updated','Обновлено','Оновлено'],refresh:['עדכון','Refresh','Обновить','Оновити'],welcome:['שלום','Hello','Здравствуйте','Вітаємо'],secure:['מחיר מהנהג. האישור אצלך.','Driver quotes. You decide.','Цену предлагает водитель. Решаете вы.','Ціну пропонує водій. Вирішуєте ви.'],payment:['התשלום לנהג בהגעה ליעד, לפי המחיר שאושר. לא מתבצעת גבייה באפליקציה.','Pay the driver on arrival at the destination, at the accepted price. No in-app collection.','Оплата водителю по прибытии в пункт назначения по согласованной цене. Без списания в приложении.','Оплата водієві після прибуття до пункту призначення за погодженою ціною. Без списання в застосунку.'],
 botDriver:['הרשמה ואישור נהג מתבצעים בשיחה עם הבוט באמצעות /driver.','Driver registration and approval are handled in the bot with /driver.','Регистрация водителя — в боте через /driver.','Реєстрація водія — у боті через /driver.'],lastLocation:['המיקום האחרון ששותף','Last shared location','Последняя геопозиция','Остання геопозиція']};
let state=null, lang='he', tab='ride', role='passenger', demo=false, busy=false, selectedRoute='', destination='', count=1, snapshotKey='', mapKey='';
const tr=k=>(words[k]||[k,k,k,k])[['he','en','ru','uk'].indexOf(lang)]||k;
const money=n=>new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(n/100)+' ₴';
const tg=window.Telegram?.WebApp;
const inboxUI=new UmanNotifications({act,openRide:()=>{tab='ride';snapshotKey='';render();$('#content').scrollIntoView({block:'start'});}});
let refreshing=false, stateGeneration=0;
const rideMap=L.map('map',{zoomControl:false}).setView([49.0,31.0],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(rideMap);L.control.zoom({position:'bottomleft'}).addTo(rideMap);let locationMarker=null;
function headers(){return {'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(demo?{'X-Demo-Role':role}:{})};}
function error(message){$('#error').textContent=message;$('#error').hidden=false;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,2800);}
async function request(url,body){const res=await fetch(url,{method:body?'POST':'GET',headers:headers(),...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error||'ACTION_UNAVAILABLE');return data;}
async function act(action,values={}){if(busy)return;busy=true;stateGeneration++;$('#error').hidden=true;$('#content').querySelectorAll('button').forEach(b=>b.disabled=true);try{state=await request('/api/action',{action,request_id:crypto.randomUUID(),...values});snapshotKey='';render();return true;}catch(e){error(e.message==='OPEN_IN_TELEGRAM'?tr('auth'):e.message==='GPS_REQUIRED'?tr('gpsText'):tr('error'));return false;}finally{busy=false;$('#content').querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function refresh(){
 if(busy||refreshing)return;
 refreshing=true;
 const generation=stateGeneration;
 try{const next=await request('/api/state');if(generation!==stateGeneration)return;state=next;render();inboxUI.connection(true);}
 catch(e){if(generation!==stateGeneration)return;inboxUI.connection(false);error(e.message==='OPEN_IN_TELEGRAM'?tr('auth'):tr('error'));if(!state)$('#content').innerHTML=`<div class="gps-icon">↗</div><h1>UMAN2GO</h1><p>${tr('auth')}</p>`;}
 finally{refreshing=false;}
}
function button(label,action,extra='',className='primary'){return `<button class="${className}" data-action="${action}" ${extra}>${esc(label)}</button>`;}
function summary(r){return `<div class="summary"><span>${esc(tr('pickupPoint'))}</span><strong>${esc(r.pickup.replace('https://maps.google.com/?q=','GPS: '))}</strong><span>↓</span><strong>${esc(r.destination)}</strong><span>${r.passengers} ${esc(tr('passengers'))}</span></div>`;}
function booking(){return `<div class="welcome-name">${tr('welcome')}, ${esc(state.user.name)}</div><h1>${tr('title')}</h1><p>${tr('subtitle')}</p><div class="locations"><div class="location-row"><span class="point"></span><span class="pickup-label">${tr('pickup')}</span>${button(tr('refresh'),'gps','','small-button')}</div><div class="route-line"></div><div class="location-row"><span class="point end"></span><input id="destination" placeholder="${tr('destination')}" aria-label="${tr('destination')}" value="${esc(destination)}" maxlength="400"></div></div><label class="label" for="route-select">${tr('popular')}</label><select id="route-select" class="quote-input"><option value="">${tr('custom')}</option>${state.routes.map(r=>`<option value="${esc(r.id)}" ${selectedRoute===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select><div class="count-row"><strong>${tr('passengers')}</strong><div class="counter"><button data-count="-1" aria-label="-1">−</button><input id="count" type="number" min="1" max="50" value="${count}" aria-label="${tr('passengers')}"><button data-count="1" aria-label="+1">+</button></div></div>${button(tr('request'),'book')}<div class="notice">${tr('priceNote')}<br>${tr('payment')}</div>`;}
function offers(r){return `<span class="status-pill">${tr('searching')}</span><h1>${tr(state.offers.length?'offers':'waiting')}</h1><p>${tr('waitingText')}</p>${summary(r)}${state.offers.length?state.offers.map(o=>`<div class="offer"><div class="offer-head"><div class="avatar">${esc(o.name[0])}</div><div class="driver-detail"><strong>${esc(o.name)}</strong><small>${esc(o.vehicle)}</small><small>${esc(o.rating)}</small></div><div class="price">${money(o.price)}</div></div><small class="label">${tr('total')}</small>${button(tr('choose'),'choose',`data-driver="${o.driver_id}"`)}</div>`).join(''):`<div class="empty">${tr('searching')}…</div>`}${button(tr('cancel'),'cancel','','danger')}`;}
function activeRide(r){const ownDriver=r.driver_id===state.user.id,d=r.assigned_driver,step=['accepted','arrived','in_progress'].indexOf(r.status);return `<span class="status-pill">#${r.id} · ${tr(r.status)}</span><h1>${tr(ownDriver&&r.status==='accepted'?'driverAccepted':r.status)}</h1><div class="status-steps">${[0,1,2].map(n=>`<i class="${n<=step?'done':''}"></i>`).join('')}</div>${d?`<div class="offer-head"><div class="avatar">${esc(d.name[0])}</div><div class="driver-detail"><strong>${esc(d.name)}</strong><small>${esc(d.vehicle)} · ${esc(d.plate)}</small></div><div class="price">${money(r.price)}</div></div>`:''}${summary(r)}${ownDriver?button(tr(({accepted:'arrive',arrived:'start',in_progress:'finish'})[r.status]),'move',`data-status="${({accepted:'arrived',arrived:'in_progress',in_progress:'completed'})[r.status]}"`):`<div class="inline-actions"><a class="secondary link" href="tel:${esc(d.phone)}">${tr('call')}</a>${button(tr('location'),'gps','','secondary')}</div>`}${state.partner_location?`<div class="notice">${tr('lastLocation')} · ${new Date(state.partner_location.updated_at*1000).toLocaleTimeString(lang)}</div>`:''}<h3>${tr('chat')}</h3><div class="chat">${state.messages.length?state.messages.map(m=>`<div class="bubble ${m.mine?'mine':''}">${esc(m.text)}${m.media?' ◧':''}</div>`).join(''):`<small>${tr('noMessages')}</small>`}</div><form id="chat-form" class="chat-form"><input id="message" placeholder="${tr('message')}" aria-label="${tr('message')}" maxlength="3500" required><button>${tr('send')}</button></form><div class="notice">${tr('payment')}</div>${!ownDriver&&r.status!=='in_progress'?button(tr('cancel'),'cancel','','danger'):''}`;}
function driverView(){const d=state.driver;if(!d||d.approval!=='approved')return `<h1>${tr('driverTitle')}</h1><p>${tr('botDriver')}</p>`;return `<div class="welcome-name">${tr('welcome')}, ${esc(state.user.name)}</div><h1>${tr('driverTitle')}</h1><p>${tr(d.available?'online':'offline')}</p>${button(tr(d.available?'goOffline':'goOnline'),'available')}<div class="notice">${tr('priceNote')}<br>${tr('payment')}</div>${state.jobs.length?state.jobs.map(r=>`<article class="offer"><h3>#${r.id} · ${esc(r.destination)}</h3><small>${r.passengers} ${tr('passengers')}</small>${r.offer_status==='priced'?`<p>${tr('offered')}</p><strong>${money(r.offered_price)}</strong>`:`<label class="label" for="price-${r.id}">${tr('price')}</label><input class="quote-input" id="price-${r.id}" type="number" min="0.01" step="0.01" max="100000" placeholder="₴"><div class="inline-actions">${button(tr('quote'),'quote',`data-ride="${r.id}"`)}${button(tr('decline'),'decline',`data-ride="${r.id}"`,'secondary')}</div>`}</article>`).join(''):`<div class="empty">${tr('noJobs')}</div>`}`;}
function history(){return `<h1>${tr('history')}</h1>${state.history.length?state.history.map(r=>`<article class="offer"><span class="label">#${r.id} · ${tr(r.status)}</span><h3>${esc(r.destination)}</h3><div>${r.price?money(r.price):'—'}</div>${r.status==='completed'?`<p>${tr('payment')}</p><p>${esc(r.distance_text)}</p>`:''}${r.status==='completed'&&r.passenger_id===state.user.id?(r.stars?`<p>${'★'.repeat(r.stars)}</p>`:`<p>${tr('rate')}</p><div class="stars">${[1,2,3,4,5].map(n=>`<button data-action="rate" data-ride="${r.id}" data-stars="${n}" aria-label="${n} / 5">${n}★</button>`).join('')}</div>`):''}</article>`).join(''):`<div class="empty">${tr('noHistory')}</div>`}`;}
function render(){if(!state)return;lang=state.user.lang;inboxUI.update(state);const key=JSON.stringify([state,tab,selectedRoute]);if(snapshotKey===key)return;snapshotKey=key;document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';$('#language').value=lang;$('#tab-ride').textContent=tr('ride');$('#tab-history').textContent=tr('history');$('#secure').textContent=tr('secure');$('#region').textContent=tr('subtitle');$('#map-caption').textContent=tr('subtitle');$('#map-label').textContent=tr('subtitle');$('.tabs').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));const focus=document.activeElement?.id,value=focus?document.activeElement.value:null;let html;if(state.gps_required)html=`<div class="gate"><div class="eyebrow">UMAN2GO / RIDE WITH CONFIDENCE</div><div class="gps-icon">⌖</div><h1>${tr('gpsTitle')}</h1><p>${tr('gpsText')}</p>${button(tr(demo?'demoGPS':'gps'),'gps')}<div class="trust"><b>⌾</b><span>${tr('gpsTrust')}</span></div></div>`;else if(tab==='history')html=history();else if(state.ride)html=['accepted','arrived','in_progress'].includes(state.ride.status)?activeRide(state.ride):offers(state.ride);else html=state.driver?driverView():booking();$('#content').innerHTML=html;if(focus&&$('#'+focus)&&value!==undefined){$('#'+focus).value=value;$('#'+focus).focus();}const position=state.partner_location||state.gps;if(position){const lat=Number(position.latitude),lon=Number(position.longitude);const mkey=lat.toFixed(5)+','+lon.toFixed(5);if(mapKey!==mkey){mapKey=mkey;rideMap.setView([lat,lon],15);if(locationMarker)locationMarker.setLatLng([lat,lon]);else locationMarker=L.marker([lat,lon],{icon:L.divIcon({className:'position-marker',iconSize:[24,24],iconAnchor:[12,12]})}).addTo(rideMap);}$('#map-label').textContent=tr(state.partner_location?'lastLocation':'pickup');}}
async function gps(){try{let position;if(demo)position={latitude:role==='driver'?48.751:48.748,longitude:30.223};else if(tg?.LocationManager&&tg.isVersionAtLeast('8.0')){const manager=tg.LocationManager;await new Promise(resolve=>manager.init(resolve));position=await new Promise((resolve,reject)=>manager.getLocation(p=>p?resolve(p):reject(new Error('GPS'))));}else{position=(await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}))).coords;}await act('location',{latitude:position.latitude,longitude:position.longitude});}catch{error(tr('denied'));}}
$('#content').addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b||busy)return;if(b.dataset.route){selectedRoute=b.dataset.route;destination=state.routes.find(r=>r.id===selectedRoute).name;snapshotKey='';render();return;}if(b.dataset.count){count=Math.max(1,Math.min(50,count+Number(b.dataset.count)));$('#count').value=count;return;}const a=b.dataset.action,rid=Number(b.dataset.ride||state.ride?.id);if(a==='gps')return gps();if(a==='book'){const ok=await act('book',{route:selectedRoute,destination,passengers:count});if(ok){destination='';selectedRoute='';}return;}if(a==='choose')return act('choose',{ride_id:rid,driver_id:Number(b.dataset.driver)});if(a==='cancel')return act('cancel',{ride_id:rid});if(a==='move')return act('move',{ride_id:rid,status:b.dataset.status});if(a==='available')return act('available',{available:!state.driver.available});if(a==='quote')return act('quote',{ride_id:rid,price:$('#price-'+rid).value});if(a==='decline')return act('decline',{ride_id:rid});if(a==='rate')return act('rate',{ride_id:rid,stars:Number(b.dataset.stars)});});
$('#content').addEventListener('input',ev=>{if(ev.target.id==='destination'){destination=ev.target.value;selectedRoute='';$('#route-select').value='';}if(ev.target.id==='count')count=Number(ev.target.value);});
$('#content').addEventListener('change',ev=>{if(ev.target.id==='route-select'){selectedRoute=ev.target.value;destination=selectedRoute?state.routes.find(r=>r.id===selectedRoute).name:'';snapshotKey='';render();}});
$('#content').addEventListener('submit',async ev=>{if(ev.target.id==='chat-form'){ev.preventDefault();if(await act('message',{ride_id:state.ride.id,text:$('#message').value}))$('#message').value='';}});
$('.tabs').addEventListener('click',ev=>{if(ev.target.dataset.tab){tab=ev.target.dataset.tab;render();}});$('#language').addEventListener('change',ev=>act('language',{language:ev.target.value}));$('#recenter').addEventListener('click',gps);
$('#switch-role').addEventListener('click',()=>{stateGeneration++;role=role==='driver'?'passenger':'driver';$('#switch-role').textContent=role==='driver'?'מעבר לנוסע':'מעבר לנהג';tab='ride';state=null;snapshotKey='';refresh();});
(async()=>{tg?.ready();tg?.expand();try{const config=await request('/api/config');demo=config.demo;$('#demo').hidden=!demo;await refresh();setInterval(()=>{if(!document.hidden)refresh();},3000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('online',refresh);}catch{error(tr('error'));}})();


